black:
  max:
  - 115
  - 135
  - 185
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 164
  - 203
  - 120
  min:
  - 0
  - 78
  - 0
green:
  max:
  - 252
  - 109
  - 207
  min:
  - 0
  - 48
  - 94
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 173
  - 130
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
